/* eslint-disable */

exports.nextSingleResponse = {
  "total": 1,
  "launches": [{
    "id": 1234,
    "name": "Ariane 5 ECA | SGDC 1 & Koreasat 7",
    "windowstart": "April 7, 2017 00:00:00 UTC",
    "windowend": "April 7, 2017 00:00:00 UTC",
    "net": "April 7, 2017 00:00:00 UTC",
    "wsstamp": 0,
    "westamp": 0,
    "netstamp": 0,
    "isostart": "20170407T000000Z",
    "isoend": "20170407T000000Z",
    "isonet": "20170407T000000Z",
    "status": 2,
    "inhold": 0,
    "tbdtime": 1,
    "vidURLs": [],
    "vidURL": null,
    "infoURLs": [],
    "infoURL": null,
    "holdreason": null,
    "failreason": null,
    "tbddate": 0,
    "probability": -1,
    "hashtag": null,
    "location": {
      "pads": [{
        "id": 147,
        "name": "Unknown, Xichang Satellite Launch Center",
        "infoURL": "Unknown",
        "wikiURL": "https:\/\/en.wikipedia.org\/wiki\/Xichang_Satellite_Launch_Center",
        "mapURL": "https:\/\/www.google.com\/maps?ll=28.246017,102.026556&q=28.246017,102.026556&hl=en&t=m&z=15",
        "latitude": 28.246017,
        "longitude": 102.026556,
        "agencies": [{
          "id": 17,
          "name": "China National Space Administration",
          "abbrev": "CNSA",
          "countryCode": "CHN",
          "type": 1,
          "infoURL": "http:\/\/www.cnsa.gov.cn\/",
          "wikiURL": "http:\/\/en.wikipedia.org\/wiki\/China_National_Space_Administration",
          "infoURLs": ["http:\/\/www.cnsa.gov.cn\/"]
        }]
      }],
      "id": 25,
      "name": "Xichang Satellite Launch Center, People's Republic of China",
      "infoURL": "",
      "wikiURL": "",
      "countryCode": "CHN"
    },
    "rocket": {
      "id": 69,
      "name": "Long March 3B\/E",
      "configuration": "B\/E",
      "familyname": "Long March 3",
      "agencies": [{
        "id": 88,
        "name": "China Academy of Space Technology",
        "abbrev": "CASC",
        "countryCode": "CHN",
        "type": 3,
        "infoURL": "http:\/\/www.cast.cn\/CastEn\/",
        "wikiURL": "http:\/\/en.wikipedia.org\/wiki\/China_Academy_of_Space_Technology",
        "infoURLs": ["http:\/\/www.cast.cn\/CastEn\/"]
      }],
      "wikiURL": "https:\/\/en.wikipedia.org\/wiki\/Long_March_3B",
      "infoURLs": [],
      "imageURL": "https:\/\/s3.amazonaws.com\/launchlibrary\/RocketImages\/placeholder_1920.png",
      "imageSizes": [320, 480, 640, 720, 768, 800, 960, 1024, 1080, 1280, 1440, 1920]
    },
    "missions": []
  }],
  "offset": 0,
  "count": 1
};

exports.nextMultiResponse = {
  "total": 5,
  "launches": [{
    "id": 1234,
    "name": "Ariane 5 ECA | Intelsat 33e & Intelsat 36",
    "windowstart": "August 24, 2016 22:00:00 UTC",
    "windowend": "August 24, 2016 22:22:00 UTC",
    "net": "August 24, 2016 22:16:01 UTC",
    "wsstamp": 1472076000,
    "westamp": 1472077320,
    "netstamp": 1472076961,
    "isostart": "20160824T220000Z",
    "isoend": "20160824T222200Z",
    "isonet": "20160824T221601Z",
    "status": 3,
    "inhold": 0,
    "tbdtime": 0,
    "vidURLs": ["https:\/\/www.youtube.com\/watch?v=TmJQjmeeDmw", "https:\/\/www.youtube.com\/watch?v=Vlt1qtme14U", "https:\/\/www.youtube.com\/watch?v=BYCOrMUrj5k"],
    "vidURL": null,
    "infoURLs": [],
    "infoURL": null,
    "holdreason": null,
    "failreason": null,
    "tbddate": 0,
    "probability": -1,
    "hashtag": null,
    "location": {
      "pads": [{
        "id": 137,
        "name": "Ariane Launch Area 3, Kourou",
        "infoURL": "http:\/\/www.esa.int\/Our_Activities\/Launchers\/Europe_s_Spaceport\/Europe_s_Spaceport2",
        "wikiURL": "http:\/\/en.wikipedia.org\/wiki\/ELA-3",
        "mapURL": "https:\/\/www.google.com\/maps\/?q=5.239000000000000,-52.769000000000000",
        "latitude": 5.239,
        "longitude": -52.768,
        "agencies": [{
          "id": 115,
          "name": "Arianespace",
          "abbrev": "ASA",
          "countryCode": "FRA",
          "type": 3,
          "infoURL": "http:\/\/www.arianespace.com",
          "wikiURL": "http:\/\/en.wikipedia.org\/wiki\/Arianespace",
          "infoURLs": ["http:\/\/www.arianespace.com"]
        }]
      }],
      "id": 3,
      "name": "Kourou, French Guiana",
      "infoURL": "",
      "wikiURL": "",
      "countryCode": "GUF"
    },
    "rocket": {
      "id": 27,
      "name": "Ariane 5 ECA",
      "configuration": "ECA",
      "familyname": "Ariane",
      "agencies": [{
        "id": 115,
        "name": "Arianespace",
        "abbrev": "ASA",
        "countryCode": "FRA",
        "type": 3,
        "infoURL": "http:\/\/www.arianespace.com",
        "wikiURL": "http:\/\/en.wikipedia.org\/wiki\/Arianespace",
        "infoURLs": ["http:\/\/www.arianespace.com"]
      }, {
        "id": 116,
        "name": "EADS Astrium Space Transportation",
        "abbrev": "EADS",
        "countryCode": "FRA",
        "type": 3,
        "infoURL": "http:\/\/www.astrium.eads.net\/en\/prog\/?family=1",
        "wikiURL": "http:\/\/en.wikipedia.org\/wiki\/EADS_Astrium_Space_Transportation",
        "infoURLs": ["http:\/\/www.astrium.eads.net\/en\/prog\/?family=1"]
      }, {
        "id": 81,
        "name": "Astrium Satellites",
        "abbrev": "EADS",
        "countryCode": "FRA,DEU,ESP,GBR",
        "type": 3,
        "infoURL": "http:\/\/www.astrium.eads.net\/",
        "wikiURL": "http:\/\/en.wikipedia.org\/wiki\/Astrium_Satellites",
        "infoURLs": ["http:\/\/www.astrium.eads.net\/"]
      }, {
        "id": 27,
        "name": "European Space Agency",
        "abbrev": "ESA",
        "countryCode": "AUT,BEL,CZE,DNK,FIN,FRA,DEU,GRC,IRE,ITA,LUZ,NLD,NOR,POL,PRT,ROU,ESP,SWE,CHE,GBR",
        "type": 2,
        "infoURL": "http:\/\/www.esa.int\/",
        "wikiURL": "http:\/\/en.wikipedia.org\/wiki\/European_Space_Agency",
        "infoURLs": ["http:\/\/www.esa.int\/"]
      }],
      "wikiURL": "https:\/\/en.wikipedia.org\/wiki\/Ariane_5",
      "infoURLs": ["http:\/\/www.arianespace.com\/vehicle\/ariane-5\/"],
      "infoURL": "http:\/\/www.arianespace.com\/vehicle\/ariane-5\/",
      "imageSizes": [320, 480, 640, 720, 768, 800, 960, 1024, 1080, 1280, 1440, 1920],
      "imageURL": "https:\/\/s3.amazonaws.com\/launchlibrary\/RocketImages\/Ariane+5+ECA_1920.jpg"
    },
    "missions": [{
      "id": 302,
      "name": "Intelsat 33e & Intelsat 36",
      "description": "Intelsat 33e and Intelsat 36 are communication satellites. Intelsat 33e will cover Europe, Africa, Asia and the Middle East. Intelsat 36 will cover Africa and South Asia. Both contain C-band transponders, Ku-band transponders and have an expected life span or about 15 years.",
      "type": 10,
      "typeName": "Communications"
    }]
  }, {
    "id": 12342,
    "name": "Long March 4C | Gaofen-10",
    "windowstart": "August 31, 2016 18:46:00 UTC",
    "windowend": "August 31, 2016 19:11:00 UTC",
    "net": "August 31, 2016 18:55:00 UTC",
    "wsstamp": 1472669160,
    "westamp": 1472670660,
    "netstamp": 1472669700,
    "isostart": "20160831T184600Z",
    "isoend": "20160831T191100Z",
    "isonet": "20160831T185500Z",
    "status": 4,
    "inhold": 0,
    "tbdtime": 0,
    "vidURLs": [],
    "vidURL": null,
    "infoURLs": [],
    "infoURL": null,
    "holdreason": null,
    "failreason": "Unknown.",
    "tbddate": 0,
    "probability": -1,
    "hashtag": null,
    "location": {
      "pads": [{
        "id": 116,
        "name": "Unknown Pad, Taiyuan",
        "infoURL": "",
        "wikiURL": "",
        "mapURL": "",
        "latitude": 38.849,
        "longitude": 111.608,
        "agencies": []
      }],
      "id": 2,
      "name": "Taiyuan, People's Republic of China",
      "infoURL": "",
      "wikiURL": "",
      "countryCode": "CHN"
    },
    "rocket": {
      "id": 70,
      "name": "Long March 4C",
      "configuration": "C",
      "familyname": "Long March 4",
      "agencies": [{
        "id": 88,
        "name": "China Academy of Space Technology",
        "abbrev": "CASC",
        "countryCode": "CHN",
        "type": 3,
        "infoURL": "http:\/\/www.cast.cn\/CastEn\/",
        "wikiURL": "http:\/\/en.wikipedia.org\/wiki\/China_Academy_of_Space_Technology",
        "infoURLs": ["http:\/\/www.cast.cn\/CastEn\/"]
      }],
      "wikiURL": "https:\/\/en.wikipedia.org\/wiki\/Long_March_4C",
      "infoURLs": [],
      "imageURL": "https:\/\/s3.amazonaws.com\/launchlibrary\/RocketImages\/placeholder_1920.png",
      "imageSizes": [320, 480, 640, 720, 768, 800, 960, 1024, 1080, 1280, 1440, 1920]
    },
    "missions": [{
      "id": 368,
      "name": "Gaofen-10",
      "description": "Earth observation.",
      "type": 7,
      "typeName": "Government\/Top Secret"
    }]
  }, {
    "id": 12343,
    "name": "Atlas V 401 | Cygnus CRS OA-7 (S.S. John Glenn)",
    "windowstart": "April 10, 2017 00:00:00 UTC",
    "windowend": "April 10, 2017 00:00:00 UTC",
    "net": "April 10, 2017 00:00:00 UTC",
    "wsstamp": 0,
    "westamp": 0,
    "netstamp": 0,
    "isostart": "20170410T000000Z",
    "isoend": "20170410T000000Z",
    "isonet": "20170410T000000Z",
    "status": 2,
    "inhold": 0,
    "tbdtime": 1,
    "vidURLs": ["https:\/\/www.youtube.com\/watch?v=UdmHHpAsMVw"],
    "vidURL": null,
    "infoURLs": [],
    "infoURL": null,
    "holdreason": null,
    "failreason": null,
    "tbddate": 1,
    "probability": 70,
    "hashtag": null,
    "location": {
      "pads": [{
        "id": 85,
        "name": "Space Launch Complex 41, Cape Canaveral, FL",
        "infoURL": "",
        "wikiURL": "https:\/\/en.wikipedia.org\/wiki\/Cape_Canaveral_Air_Force_Station_Space_Launch_Complex_41",
        "mapURL": "http:\/\/maps.google.com\/maps?f=q&amp;hl=en&amp;q=28.5834+N,+80.5829+W&amp;ie=UTF8&amp;z=17&amp;ll=28.583646,-80.582904&amp;spn=0.004211,0.010815&amp;t=h&amp;om=0&amp;iwloc=addr",
        "latitude": 28.58341025,
        "longitude": -80.58303644,
        "agencies": [{
          "id": 124,
          "name": "United Launch Alliance",
          "abbrev": "ULA",
          "countryCode": "USA",
          "type": 3,
          "infoURL": "http:\/\/www.ulalaunch.com\/",
          "wikiURL": "http:\/\/en.wikipedia.org\/wiki\/United_Launch_Alliance",
          "infoURLs": ["http:\/\/www.ulalaunch.com\/"]
        }, {
          "id": 161,
          "name": "United States Air Force",
          "abbrev": "USAF",
          "countryCode": "USA",
          "type": 1,
          "infoURL": "http:\/\/www.af.mil",
          "wikiURL": "http:\/\/en.wikipedia.org\/wiki\/United_States_Air_Force",
          "infoURLs": ["http:\/\/www.af.mil"]
        }]
      }],
      "id": 16,
      "name": "Cape Canaveral, FL, USA",
      "infoURL": "",
      "wikiURL": "",
      "countryCode": "USA"
    },
    "rocket": {
      "id": 26,
      "name": "Atlas V 401",
      "configuration": "401",
      "familyname": "Atlas",
      "agencies": [{
        "id": 124,
        "name": "United Launch Alliance",
        "abbrev": "ULA",
        "countryCode": "USA",
        "type": 3,
        "infoURL": "http:\/\/www.ulalaunch.com\/",
        "wikiURL": "http:\/\/en.wikipedia.org\/wiki\/United_Launch_Alliance",
        "infoURLs": ["http:\/\/www.ulalaunch.com\/"]
      }, {
        "id": 82,
        "name": "Lockheed Martin",
        "abbrev": "LMT",
        "countryCode": "USA",
        "type": 3,
        "infoURL": "http:\/\/www.lockheedmartin.com\/",
        "wikiURL": "http:\/\/en.wikipedia.org\/wiki\/Lockheed_Martin",
        "infoURLs": ["http:\/\/www.lockheedmartin.com\/"]
      }, {
        "id": 106,
        "name": "General Dynamics",
        "abbrev": "GD",
        "countryCode": "USA",
        "type": 3,
        "infoURL": "http:\/\/www.gd.com\/",
        "wikiURL": "http:\/\/en.wikipedia.org\/wiki\/General_Dynamics",
        "infoURLs": ["http:\/\/www.gd.com\/"]
      }],
      "wikiURL": "http:\/\/en.wikipedia.org\/wiki\/Atlas_V",
      "infoURLs": [],
      "imageSizes": [320, 480, 640, 720, 768, 800, 960, 1024, 1080, 1280, 1440, 1920, 2560],
      "imageURL": "https:\/\/s3.amazonaws.com\/launchlibrary\/RocketImages\/Atlas+V+401_2560.jpg"
    },
    "missions": [{
      "id": 176,
      "name": "Cygnus CRS OA-7 (S.S. John Glenn)",
      "description": "This is the eighth planned flight of the Orbital ATK's unmanned resupply spacecraft Cygnus and its seventh flight to the International Space Station under the Commercial Resupply Services contract with NASA. Orbital ATK named the vehicle after astronaut John Glenn, the first American to orbit Earth and pioneer of human spaceflight.",
      "type": 11,
      "typeName": "Resupply"
    }]
  }, {
    "id": 12344,
    "name": "Soyuz-2.1b\/Fregat-M | Glonass-M",
    "windowstart": "April 10, 2017 00:00:00 UTC",
    "windowend": "April 10, 2017 00:00:00 UTC",
    "net": "April 10, 2017 00:00:00 UTC",
    "wsstamp": 0,
    "westamp": 0,
    "netstamp": 0,
    "isostart": "20170410T000000Z",
    "isoend": "20170410T000000Z",
    "isonet": "20170410T000000Z",
    "status": 2,
    "inhold": 0,
    "tbdtime": 0,
    "vidURLs": [],
    "vidURL": null,
    "infoURLs": [],
    "infoURL": null,
    "holdreason": null,
    "failreason": null,
    "tbddate": 1,
    "probability": -1,
    "hashtag": null,
    "location": {
      "pads": [{
        "id": 50,
        "name": "43\/3 (43L), Plesetsk Cosmodrome, Russia",
        "infoURL": "",
        "wikiURL": "",
        "mapURL": "http:\/\/maps.google.com\/maps?f=q&amp;hl=en&amp;q=62.9273+N,+40.450+E&amp;ie=UTF8&amp;z=16&amp;ll=62.92755,40.450008&amp;spn=0.004365,0.021629&amp;t=h&amp;om=0&amp;iwloc=addr",
        "latitude": 62.9273,
        "longitude": 40.45,
        "agencies": [{
          "id": 163,
          "name": "Russian Aerospace Defence Forces",
          "abbrev": "VKO",
          "countryCode": "RUS",
          "type": 1,
          "infoURL": "http:\/\/www.eng.mil.ru\/en\/structure\/forces\/cosmic.htm",
          "wikiURL": "http:\/\/en.wikipedia.org\/wiki\/Russian_Aerospace_Defence_Forces",
          "infoURLs": ["http:\/\/www.eng.mil.ru\/en\/structure\/forces\/cosmic.htm"]
        }]
      }],
      "id": 11,
      "name": "Plesetsk Cosmodrome, Russian Federation",
      "infoURL": "",
      "wikiURL": "",
      "countryCode": "RUS"
    },
    "rocket": {
      "id": 153,
      "name": "Soyuz-2.1b\/Fregat-M",
      "configuration": "-2.1b\/Fregat-M",
      "familyname": "Soyuz",
      "agencies": [{
        "id": 111,
        "name": "Progress State Research and Production Rocket Space Center",
        "abbrev": "TsSKB-Progress",
        "countryCode": "RUS",
        "type": 3,
        "infoURL": "http:\/\/www.samspace.ru\/",
        "wikiURL": "http:\/\/en.wikipedia.org\/wiki\/TsSKB-Progress",
        "infoURLs": ["http:\/\/www.samspace.ru\/"]
      }, {
        "id": 63,
        "name": "Russian Federal Space Agency (ROSCOSMOS)",
        "abbrev": "FKA",
        "countryCode": "RUS",
        "type": 1,
        "infoURL": "http:\/\/www.roscosmos.ru\/",
        "wikiURL": "http:\/\/en.wikipedia.org\/wiki\/Russian_Federal_Space_Agency",
        "infoURLs": ["http:\/\/www.roscosmos.ru\/"]
      }],
      "wikiURL": "https:\/\/en.wikipedia.org\/wiki\/Soyuz-2",
      "infoURLs": [],
      "imageURL": "https:\/\/s3.amazonaws.com\/launchlibrary\/RocketImages\/placeholder_1920.png",
      "imageSizes": [320, 480, 640, 720, 768, 800, 960, 1024, 1080, 1280, 1440, 1920]
    },
    "missions": [{
      "id": 511,
      "name": "Glonass-M",
      "description": "Glonass-M, also known as Uragan-M, are the second generation of Uragan satellite design used for GLONASS satellite navigation system. GLONASS is a Russian space-based navigation system comparable to the similar GPS and Galileo systems. This generation improves on accuracy, power consumption and design life. Each satellite weighs 1415 kg, is equipped with 12 L-band antennas, and has an operational lifetime of 7 years.",
      "type": 10,
      "typeName": "Communications"
    }]
  }, {
    "id": 12345,
    "name": "Soyuz STA\/Fregat | SES-15",
    "windowstart": "April 12, 2017 00:00:00 UTC",
    "windowend": "April 12, 2017 00:00:00 UTC",
    "net": "April 12, 2017 00:00:00 UTC",
    "wsstamp": 0,
    "westamp": 0,
    "netstamp": 0,
    "isostart": "20170412T000000Z",
    "isoend": "20170412T000000Z",
    "isonet": "20170412T000000Z",
    "status": 2,
    "inhold": 0,
    "tbdtime": 1,
    "vidURLs": ["http:\/\/www.arianespace.com\/mission\/ariane-flight-vs17\/"],
    "vidURL": null,
    "infoURLs": [],
    "infoURL": null,
    "holdreason": null,
    "failreason": null,
    "tbddate": 0,
    "probability": -1,
    "hashtag": null,
    "location": {
      "pads": [{
        "id": 146,
        "name": "Soyuz Launch Complex, Kourou\/Sinnamary",
        "infoURL": "http:\/\/www.arianespace.com\/spaceport-soyuz\/overview.asp",
        "wikiURL": "https:\/\/en.wikipedia.org\/wiki\/Ensemble_de_Lancement_Soyouz",
        "mapURL": "https:\/\/www.google.com\/maps\/?q=5.3019,-52.8346",
        "latitude": 5.3019,
        "longitude": -52.8346,
        "agencies": [{
          "id": 115,
          "name": "Arianespace",
          "abbrev": "ASA",
          "countryCode": "FRA",
          "type": 3,
          "infoURL": "http:\/\/www.arianespace.com",
          "wikiURL": "http:\/\/en.wikipedia.org\/wiki\/Arianespace",
          "infoURLs": ["http:\/\/www.arianespace.com"]
        }]
      }],
      "id": 3,
      "name": "Kourou, French Guiana",
      "infoURL": "",
      "wikiURL": "",
      "countryCode": "GUF"
    },
    "rocket": {
      "id": 76,
      "name": "Soyuz STA\/Fregat",
      "configuration": "STA\/Fregat",
      "familyname": "Soyuz",
      "agencies": [{
        "id": 111,
        "name": "Progress State Research and Production Rocket Space Center",
        "abbrev": "TsSKB-Progress",
        "countryCode": "RUS",
        "type": 3,
        "infoURL": "http:\/\/www.samspace.ru\/",
        "wikiURL": "http:\/\/en.wikipedia.org\/wiki\/TsSKB-Progress",
        "infoURLs": ["http:\/\/www.samspace.ru\/"]
      }, {
        "id": 63,
        "name": "Russian Federal Space Agency (ROSCOSMOS)",
        "abbrev": "FKA",
        "countryCode": "RUS",
        "type": 1,
        "infoURL": "http:\/\/www.roscosmos.ru\/",
        "wikiURL": "http:\/\/en.wikipedia.org\/wiki\/Russian_Federal_Space_Agency",
        "infoURLs": ["http:\/\/www.roscosmos.ru\/"]
      }],
      "wikiURL": "https:\/\/en.wikipedia.org\/wiki\/Soyuz-2_(rocket)",
      "infoURLs": [],
      "imageURL": "https:\/\/s3.amazonaws.com\/launchlibrary\/RocketImages\/placeholder_1920.png",
      "imageSizes": [320, 480, 640, 720, 768, 800, 960, 1024, 1080, 1280, 1440, 1920]
    },
    "missions": [{
      "id": 498,
      "name": "SES-15",
      "description": "SES 15 is a geostationary communications satellite operating in Ka- and Ku-bands in North America, which uses electric propulsion for initial orbit raising and all on-orbit manoeuvres.",
      "type": 10,
      "typeName": "Communications"
    }]
  }],
  "offset": 0,
  "count": 5
};
